### ISSUE TITLE
Remove binaries and Eclipse files from git repo

### ISSUE THREAD

**Issue by Gjum** [nobility-suite/DescentIntoDarkness#2]
`git rm -r --cached target/ settings/ .classpath .project`

This will delete them from the git repo, `--cache` means it'll leave the actual files on your disk.

Also add `.classpath` and `.project` to the `.gitignore` file: `echo -e 'target/\nsettings/\n.classpath\n.project' >> .gitignore`

**Comment by Earthcomputer** [comment]
Fixed
